name: Manga Crawler

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run manga crawler
        run: node index.js

      - name: Upload json file
        uses: actions/upload-artifact@v3
        with:
          name: manga-links
          path: manga_links.json

      - name: Upload Excel file
        uses: actions/upload-artifact@v3
        with:
          name: manga-details
          path: manga_details.xlsx
      # - name: Upload screenshots
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: screenshots
      #     path: '*.png'
